version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-brain-service
    ports:
      - "8002:8002"
    env_file:
      - .env.local
    environment:
      - PORT=${PORT:-8002}
    volumes:
      - ./:/app
    command: >-
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port ${PORT:-8002} --reload"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${PORT:-8002}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

